project:
  type: website
  output-dir : docs

website:
  title: "ABCD Risk Score Tools"
  navbar:
    left:
      - file: index.qmd
        text: Start Here
      - file: code-download.qmd
        text: Download the Tools
      - file: documentation.qmd
        text: Documentation for the item metadata
      - file: explore-metadata.qmd
        text: Explore the item metadata
      -  file: faq.qmd
         text: FAQs


      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

